# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'turtlenetwork docker'
    repository: 'turtlenetwork/tnnode'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '**'
    tags: |
      'latest'
      $(curl -fsSL https://api.github.com/repos/BlackTurtle123/TurtleNetwork/releases/latest | tac | grep -m 1 'tag_name.:' | tr -cd '[0-9\.]')